name: Format

on:
  pull_request:
  push:
    branches: ["main"]

jobs:
  format:
    name: Format
    runs-on: ubuntu-latest
    steps:
    - uses: stairwell-inc/checkout@v4
    - run: rustup toolchain install stable
    - run: cargo fmt -- --check
