name: Release

on:
  push:
    tags: ["v*"]
  workflow_dispatch:

jobs:
  get-version:
    runs-on: ubuntu-latest
    steps:
    - uses: stairwell-inc/checkout@v4
    - run: |
        { echo -n VERSION=
          grep '^version =' Cargo.toml | head -n1 | sed 's/version = "\(.*\)"/\1/'
        } >> $GITHUB_ENV
    outputs:
      version: ${{ env.VERSION }}

  build:
    uses: ./.github/workflows/build.yaml

  publish:
    name: Publish to Crates Registry
    needs: build
    runs-on: ubuntu-latest
    environment: crates-io
    steps:
    - uses: stairwell-inc/checkout@v4
    - run: cargo publish --no-verify --locked
      env:
        CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}

  macos-release:
    name: macOS Release
    needs: [build, get-version]
    runs-on: [self-hosted, macOS]
    environment: macos
    steps:
    - uses: stairwell-inc/checkout@v4
    - uses: stairwell-inc/download-artifact@v4
      with:
        pattern: aspect-reauth-*-apple-darwin
    - run: |
        lipo -create -output aspect-reauth-universal aspect-reauth-{x86_64,aarch64}-apple-darwin/aspect-reauth
    - run: rm -rf aspect-reauth-*-apple-darwin

    - uses: stairwell-inc/upload-artifact@v4
      with:
        name: aspect-reauth-universal-darwin
        path: aspect-reauth-universal

    - run: |
        cp aspect-reauth-universal .tmp.$$
        trap "rm -f .tmp.$$" EXIT
        codesign -s "Developer ID Application: Stairwell, Inc. (677UQVFGY8)" -f --timestamp -o runtime .tmp.$$
        chmod +x .tmp.$$
        mv .tmp.$$ aspect-reauth

    - uses: stairwell-inc/upload-artifact@v4
      with:
        name: aspect-reauth-signed-darwin
        path: aspect-reauth

    - env:
        NOTARY_PASS: ${{ secrets.NOTARY_PASS }}
        DEV_ACCOUNT: ${{ secrets.DEV_ACCOUNT }}
      run: |
        xcrun notarytool store-credentials --apple-id "$DEV_ACCOUNT" --team-id 677UQVFGY8 --password "$NOTARY_PASS" notary-aspect-reauth
        mkdir .root.$$
        trap "rm -rf .root.$$" EXIT
        cp aspect-reauth .root.$$
        pkgbuild --root .root.$$ \
                 --identifier com.stairwell.pkg.aspect-reauth \
                 --version "${{ needs.get-version.outputs.version }}" \
                 --install-location /usr/local/bin \
                 --sign "Developer ID Installer: Stairwell, Inc. (677UQVFGY8)" \
                 aspect-reauth.pkg
        xcrun notarytool submit aspect-reauth.pkg --keychain-profile notary-aspect-reauth --wait
        xcrun stapler staple aspect-reauth.pkg
        spctl --assess -vv --type install aspect-reauth.pkg

    - uses: stairwell-inc/upload-artifact@v4
      with:
        name: aspect-reauth-pkg-darwin
        path: aspect-reauth.pkg
        if-no-files-found: error

  github-release:
    needs: [build, get-version, macos-release]
    runs-on: ubuntu-latest
    steps:
    - uses: stairwell-inc/download-artifact@v4
    - env:
        VERSION: ${{ needs.get-version.outputs.version }}
      run: |
        mkdir gh-release
        ln aspect-reauth-pkg-darwin/aspect-reauth.pkg gh-release/aspect-reauth-$VERSION.pkg
        ln aspect-reauth-signed-darwin/aspect-reauth gh-release/aspect-reauth-$VERSION-darwin
        ln aspect-reauth-x86_64-unknown-linux-gnu/aspect-reauth gh-release/aspect-reauth-$VERSION-linux-amd64
        ln aspect-reauth-x86_64-pc-windows-msvc/aspect-reauth.exe gh-release/aspect-reauth-$VERSION-windows-amd64.exe
    - uses: stairwell-inc/action-gh-release@v2
      with:
        draft: true
        files: gh-release/*
        generate_release_notes: true
