name: Release

on:
  push:
    tags: ["v*"]
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/build.yaml
    with:
      release: true

  publish:
    name: Publish to crates.io
    needs: build
    runs-on: ubuntu-latest
    environment: crates-io
    steps:
    - uses: stairwell-inc/checkout@v4
    - uses: stairwell-inc/crates-io-auth-action@v1
      id: auth
    - run: cargo publish --no-verify --locked
      env:
        CARGO_REGISTRY_TOKEN: ${{ steps.auth.outputs.token }}

  macos-release:
    name: macOS Release
    needs: build
    runs-on: [self-hosted, macOS]
    environment: macos
    steps:
    - uses: stairwell-inc/checkout@v4
    - uses: stairwell-inc/download-artifact@v4
      with:
        pattern: aspect-reauth-*-apple-darwin
    - run: |
        lipo -create -output aspect-reauth-universal aspect-reauth-{x86_64,aarch64}-apple-darwin/aspect-reauth
    - run: rm -rf aspect-reauth-*-apple-darwin

    - uses: stairwell-inc/upload-artifact@v4
      with:
        name: aspect-reauth-universal-darwin
        path: aspect-reauth-universal

    - run: |
        cp aspect-reauth-universal aspect-reauth
        codesign -s "Developer ID Application: Stairwell, Inc. (677UQVFGY8)" -f --timestamp -o runtime aspect-reauth
        chmod +x aspect-reauth

    - name: Get version
      id: get-version
      run: |
        { echo -n version=
          ./aspect-reauth --version | cut -d' ' -f2
        } >> $GITHUB_OUTPUT

    - uses: stairwell-inc/upload-artifact@v4
      with:
        name: aspect-reauth-signed-darwin
        path: aspect-reauth

    - env:
        NOTARY_PASS: ${{ secrets.NOTARY_PASS }}
        DEV_ACCOUNT: ${{ secrets.DEV_ACCOUNT }}
      run: |
        xcrun notarytool store-credentials --apple-id "$DEV_ACCOUNT" --team-id 677UQVFGY8 --password "$NOTARY_PASS" notary-aspect-reauth
        mkdir .root.$$
        trap "rm -rf .root.$$" EXIT
        cp aspect-reauth .root.$$
        pkgbuild --root .root.$$ \
                 --identifier com.stairwell.pkg.aspect-reauth \
                 --version "${{ steps.get-version.outputs.version }}" \
                 --install-location /usr/local/bin \
                 --sign "Developer ID Installer: Stairwell, Inc. (677UQVFGY8)" \
                 aspect-reauth.pkg
        xcrun notarytool submit aspect-reauth.pkg --keychain-profile notary-aspect-reauth --wait
        xcrun stapler staple aspect-reauth.pkg
        spctl --assess -vv --type install aspect-reauth.pkg

    - uses: stairwell-inc/upload-artifact@v4
      with:
        name: aspect-reauth-pkg-darwin
        path: aspect-reauth.pkg
