name: Release

env:
  NOTARY_PASS: ${{ secrets.NOTARY_PASS }}
  DEV_ACCOUNT: ${{ secrets.DEV_ACCOUNT }}

on:
  push:
    tags: ["v*"]

jobs:
  build:
    uses: ./.github/workflows/build.yaml

  macos-release:
    name: macOS Release
    needs: build
    runs-on: [self-hosted, macos]
    environment: macos
    steps:
    - uses: stairwell-inc/checkout@v4
    - run: rustup target add x86_64-apple-darwin && rustup target add aarch64-apple-darwin && rustup update
    - run: cargo build --locked --release --target x86_64-apple-darwin
    - run: cargo build --locked --release --target aarch64-apple-darwin
    - run: |
      lipo -create -output aspect-reauth-universal target/{x86_64,aarch64}-apple-darwin/release/aspect-reauth
    - run: |
      set -e
      cp aspect-reauth-universal .tmp.$$
      trap "rm -f .tmp.$$" EXIT
      codesign -s 'Developer ID Application: Stairwell, Inc. (677UQVFGY8)' -f --timestamp -o runtime .tmp.$$
      mv .tmp.$$ aspect-reauth-signed
    - run: |
      set -e
      xcrun notarytool store-credentials --apple-id "$DEV_ACCOUNT" --team-id 677UQVFGY8 --password "$NOTARY_PASS" notary-aspect-reauth
      xcrun notarytool submit aspect-reauth-signed --keychain-profile notary-aspect-reauth --wait
      cp aspect-reauth-signed .tmp.$$
      trap "rm -f .tmp.$$" EXIT
      xcrun stapler staple .tmp.$$
      mv .tmp.$$ aspect-reauth
      spctl --assess -vv --type execute aspect-reauth
    - uses: stairwell-inc/upload-artifact@v4
      with:
        name: macos-release
        path: aspect-reauth*
